env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-tsdoc'
rules:
  '@typescript-eslint/no-var-requires': "error"
  '@typescript-eslint/no-unused-vars': "error"
  '@typescript-eslint/no-explicit-any': "off"
  'tsdoc/syntax': "warn"
  'prettier/prettier': "error"
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
